-- Reset test data
TRUNCATE TABLE organizations, workspaces, goals, tasks CASCADE;

-- Insert test data
INSERT INTO auth.users (id, email)
VALUES 
  ('00000000-0000-0000-0000-000000000000', 'test@example.com');

-- Other test data will be generated by the test helpers 